language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
before_install:
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=payline.test_settings
install:
  - pip install -e .
  - pip install -r requirements.txt Django==$DJANGO_VERSION
before_script:
  - flake8 payline --exclude=migrations
script:
  - make test
branches:
  only:
    - master
